Increase Fee Weight on Trader Rewards Mechanism
dydxfoundation/dip pull request #47
Opened 2022-04-05 02:37 UTC by maxholloway

2022-04-28 17:55 UTC, dgogel requested changes
You should also change your file name to DIP-10

2022-04-28 17:55 UTC, dgogel commented on content/dips/DIP-increase-fee-weight.md
> +DIP: <to be assigned>
it should be DIP :10

2022-05-07 20:34 UTC, AnneJHBTC commented
good!

2022-05-09 10:55 UTC, dgogel approved these changes

2022-05-09 10:56 UTC, merged